# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/oop_lab_db
spring.datasource.username=postgres
spring.datasource.password=fayetot
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings
# 'update' automatically creates tables for your Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Server Port (Keep at 8080 or change to 8081 if 8080 is blocked)
server.port=8080