spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/idoldb
spring.datasource.username=postgres
spring.datasource.password=JENNIE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true