spring.application.name=demo

# H2 config (comment out)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driverClassName=org.h2.Driver
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=false

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/idoldb
spring.datasource.username=postgres
spring.datasource.password=JENNIE
spring.jpa.hibernate.ddl-auto=update
