spring.application.name=app
# spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/yourdb
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update
