spring.application.name=api-demo

# Server configuration
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL // revoke comment format if test
#spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
#spring.datasource.username=postgres
#spring.datasource.password=yourpassword

# H2 Dependency
runtimeOnly 'com.h2database:h2'

# PostGresq
runtimeOnly 'org.postgresql:postgresql'

# Application info
app.name=Go Spring Boot API
app.version=1.0.0

# Logging
logging.level.com.go.springboot=DEBUG