spring.application.name=fullstack

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/fullstackdb
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Allow cross-origin requests from React frontend
spring.web.cors.allowed-origins=http://localhost:5173