package com.caneda.springboot.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserRequestDTO {
    private String userName;
    private String userEmail;
    private int userAge;
    // no id - auto generated by DB
    // no userWalletAmount - shouldn't be set on creation
}