spring.application.name=api-demo

# Server configuration
server.port=8070

# H2 Database uncomment and comment out H2 above to switch)
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL (uncomment and comment out H2 above to switch)
#spring.datasource.url=jdbc:postgresql://localhost:5432/navarrodb
#spring.datasource.username=postgres
#spring.datasource.password=yourpassword

# App info
app.name=Navarro Spring Boot API
app.version=1.0.0
logging.level.com.navarro.springboot=DEBUG